FROM us-west1-docker.pkg.dev/gcp-security-dev-curriculum/elmer-repo/elmerbase:0.0.6

WORKDIR /physics
COPY ELMERSOLVER_STARTINFO waveguide.sif run_elmer.sh /physics/
COPY shoebox_tets /physics/shoebox_tets
